version: '3.8'

services:
  # Next.js 應用程式
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/flowquest?authSource=admin
      - MONGODB_DB_NAME=flowquest
    depends_on:
      - mongo
    networks:
      - flowquest-network

  # MongoDB 資料庫
  mongo:
    image: mongo:7.0
    container_name: flowquest-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: flowquest
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - flowquest-network

  # MongoDB Express (Web UI，可選)
  mongo-express:
    image: mongo-express:1.0.2
    container_name: flowquest-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    networks:
      - flowquest-network

volumes:
  mongo-data:
    driver: local

networks:
  flowquest-network:
    driver: bridge